version: "3.9"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    # volumes -> for saving dashboard and configuration data
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
      
-----------------------------

# Grafana Stack: monitoring

# Grafana - Dashboards 
# Prometheus - Metrics DB -> pulling / scrape
# Loki - Logs DB -> push event


# Datadog
# Logs.io
# CloudWatch -> AWS
# Grafana - Cloud / On Prem
# ELK Stack
# GCP Monitoring service
# AZURE Monitoring service


# 1. terminal/console output
# 2. loges save in file
# 3. send the logs to some endpoint (loki)


# linux -> node exporter
# windows -> windows exporter
# docker containers -> cAdvisor exporter

# k8s exporter
